name: Snyk Scan
on:
  pull_request:
    branches:
      - main
jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk auth $SNYK_TOKEN
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
